# https://martin-thoma.com/configuration-files-in-python/
# POSTGRES_ADDRESS = '' ## INSERT YOUR DB ADDRESS IS LOCALHOST
# POSTGRES_PORT = '' ## PORT NUMBER
# POSTGRES_USERNAME = ''     ## CHANGE THIS TO YOUR POSTGRES USERNAME
POSTGRES_PASSWORD = 'postgres' ## CHANGE THIS TO YOUR POSTGRES PASSWORD
# POSTGRES_DBNAME = '' ## CHANGE THIS TO YOUR DATABASE NAME